# inside .github/workflows/your-action.yml
name: Add File to Bucket
on: 
  push:
    branches: [ master ]

jobs:
  deploy:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2
  
        - name: Run a one-line script
          run: echo Hello, world!
  
        - name: Run a multi-line script
          run: |
            echo Add other actions to build,
            echo test, and deploy your project.
  
  upload: 
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@master
     - uses: keithweaver/aws-s3-github-action@v1.0.0 
       with:
         source: "./README.md"
         destination: "s3://vd-experiments/GithubActions/"
         aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws_region: 'us-east-2'
