# inside .github/workflows/your-action.yml
name: Add File to Bucket
on: 
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
     # - uses: actions/checkout@master  
     # - uses: ramonpaolo/action-upload-s3@main
     #   env:
     #    FILE: README.md
     #    AWS_REGION: 'us-east-2'
     #    S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
     #    S3_KEY: ${{ secrets.S3_KEY }}
     #    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
     #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
